using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Fano
{
    public class DictionaryGenerator
    {
        private readonly List<WordFrequency> _frequencyTable;
        /*
         * Dictionary 'key' is a decimal representention of bit sequence.
         * In compression proccess we will use words (bit sequence, ussualy would be a char size) as keys
         * to compress into codes which are dictionary vallues
        */
        private Dictionary<int, BitArray> _dictionary;  
        private readonly int[] _bitWords; //a copy of dictionary 'keys'

        public static Dictionary<int, BitArray> For(List<WordFrequency> frequencies)
        {
            return new DictionaryGenerator(frequencies).GenerateDictionaryValues();
        }

        private DictionaryGenerator( List<WordFrequency> sortedFrequencyTable )
        {
            if (sortedFrequencyTable == null)
                throw new ArgumentException("BitArray must not be null");

            this._frequencyTable = sortedFrequencyTable;

            _dictionary = Enumerable.Range(0, sortedFrequencyTable.Count).ToDictionary(x => GetIntFromBitArray(x), x => (BitArray)null);
            _bitWords = _dictionary.Select(x => x.Key).ToArray();
        }

        private Dictionary<int, BitArray>  GenerateDictionaryValues()
        {
            FanoAlgorithm(0, _dictionary.Count - 1);

            return _dictionary;
        }

        /*
        * The Fano algorithm operates on a sorted list of 'words' based on their frequencies.
        * In this implementation, the list is sorted in descending order. The algorithm recursively divides the array into halves,
        * assigning 0 to one half and 1 to the other. This process continues until each subarray contains only one member.
        * The unique code representation is generated by combining the assigned 0's and 1's for each division.
        */
        private void FanoAlgorithm(int left, int right)
        {
            if (left == right)
            {
                return;
            }

            int index = GetArraySplitIndex(left, right);

            AddBits(left, index, right);

            FanoAlgorithm(left, index);
            FanoAlgorithm(index + 1, right);
        }

        //Assigns 0 or 1 value toe the left to index side of the array
        private void AddBits(int left, int index, int right)
        {
            for (int i = left; i <= right; i++)
            {
                bool value = i <= index ? false : true;
                AddBit(i, value);
            }
        }


        // ads a parrameter bit to the 'code' sequence
        private void AddBit(int index, bool value)
        {
            if (_dictionary[_bitWords[index]] == null)
            {
                _dictionary[_bitWords[index]] = new BitArray(new[] { value });
                return;
            }

            BitArray currentArray = _dictionary[_bitWords[index]];
            BitArray newArray =  new BitArray(currentArray.Length + 1);

            for (int i = 0; i < currentArray.Length; i++)
            {
                newArray[i] = currentArray[i];
            }

            newArray[newArray.Length - 1] = value;

            _dictionary[_bitWords[index]] = newArray;
        }

        private int GetArraySplitIndex(int left, int right)
        {
            int maxArraySum = TotalFrequency(left, right);
            int arraySum = 0;

            for (int index = left; index < right; index++)
            {
                arraySum += _frequencyTable[index].Frequency;
                int nextArraySum = arraySum + _frequencyTable[index + 1].Frequency;

                int difference = Math.Abs(arraySum - (maxArraySum - arraySum));
                int nextDifference = Math.Abs(nextArraySum - (maxArraySum - nextArraySum));

                if (difference <= nextDifference)
                {
                    return index;
                }
            }

            throw new InvalidOperationException("Split index not found.");
        }

        private int TotalFrequency(int left, int right)
        {
            int sum = 0;

            for (int i = left; i <= right; i++)
            {
                sum += _frequencyTable[i].Frequency;
            }

            return sum;
        }

        private int GetIntFromBitArray(int index)
        {
            int sum = 0;

            foreach( bool bit in _frequencyTable[index].Bits )
            {
                sum = sum * 2 + (bit ? 1 : 0);
            }

            return sum;
        }
    }
}
